name: Expo Prebuild (ios + android)

on:
  workflow_dispatch:

jobs:
  prebuild:
    runs-on: macos-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: |
          npm install -g expo-cli
          npm ci

      - name: Gerar pastas nativas
        run: |
          npx expo prebuild --platform all --no-install

      - name: Upload das pastas como artefato
        uses: actions/upload-artifact@v4
        with:
          name: pastas-nativas
          path: |
            ios
            android
